### ISSUE TITLE
Ubuntu18.04启动yobot时报错

### ISSUE THREAD

**Issue by wenp5454** [pcrbot/yobot-docs#1]
按照linux部署的步骤来的，mirai可以正常启动，yobot启动时报错[2020-08-23 01:18:24,168] ASGI Framework Lifespan error, continuing without Lifespan support，可以正常进入网页端但qq私聊或者群聊没有反应，希望大佬指点一二
![QQ截图20200823011942](https://user-images.githubusercontent.com/65849057/90961925-c956c100-e4de-11ea-8e27-46278c2d285e.png)

**Comment by wenp5454** [comment]
而在使用docker部署的时候，在最后启动时会出现entry.sh报错，然后看上去是将所有配置文件重置后再写入到容器里导致无法登陆，不知道这个有没有什么解决办法
![QQ截图20200823160551](https://user-images.githubusercontent.com/65849057/90974090-89352400-e55a-11ea-900f-d9e9f32cb5de.png)

**Comment by wenp5454** [comment]
原来是在vultr上部署的，今天换回阿里云的学生机安装完py3.6后就能正常用第一种办法运行。。就很怪，不知道是不是两家的Ubuntu的问题

**Comment by mk-ro** [comment]
> 而在使用docker部署的时候，在最后启动时会出现entry.sh报错，然后看上去是将所有配置文件重置后再写入到容器里导致无法登陆，不知道这个有没有什么解决办法
> ![QQ截图20200823160551](https://user-images.githubusercontent.com/65849057/90974090-89352400-e55a-11ea-900f-d9e9f32cb5de.png)

我也遇到了这个问题，排查了下，发现原作者的 Dockerfile 中最后一行: ENTRYPOINT ./entry.sh 这里有误，应该改成 ENTRYPOINT bash ./entry.sh。可以自己clone源码然后重新构件镜像再运行。
报错的原因如下：sh命令无法识别"[[]]"表达式， ./enrty.sh 应该是默认使用了 sh
解决办法：bash与sh是有区别的，两者是不同的命令，且bash是sh的增强版，而"[[]]"是bash脚本中的命令，因此在执行时，使用sh命令会报错，将sh替换为bash命令即可
