### ISSUE TITLE
[Question] 是否可以考虑写一个从插件版移植至独立版的教程?

### ISSUE THREAD

**Issue by asdfghjkl68qq** [pcrbot/yobot-docs#4]
根据提示yobot即将停止对插件版的支持，而目前帮助文档所展示的安装方式基本上都是立足于从零开始构建的情况，却并未考虑携带历史数据从插件版向独立版转换，同时保持其他nonebot插件在原有同一qq号下正常运作的情形，是否可以考虑编写新的移植教程？

**Comment by yuudi** [comment]
已完成 <https://yobot.win/install/transfer-from-plugin/>
